service_name: aws
bucket_name: meets_test_bucket
backups:
  - target: lib/*.rb
    upload_dir: test1
    delete?: false
    cycle: 3
  - target: invalid test
    upload_dir: test2
# hipchat:
#   token: 
#   room_id: 
#   color: gray
# mail:
#   to: to@hoge.com
#   from: from@hoge.com
#   subject: バックアップレポート
#   smtp:
#     address: smtp.gmail.com
#     port: 587
#     domain: smtp.gmail.com
#     user_name: <SMTP_USER_NAME>
#     password: <SMTP_USER_PASSWORD>
#     authentication: plain
#     enable_starttls_auto: true
